### ISSUE TITLE
permissions on runforever.sh

### ISSUE THREAD

**Issue by wracted** [JoeBanks13/Music-Butt#4]
This script has a comment above which recommends giving the file permissions of 777 which is an extremely bad idea as it gives all users of the system full r/w and execute permissions. A better idea would be to recommend running chmod +x on the file. This makes the script executable for the current user only. Thanks.

**Comment by JoeBanks13** [comment]
Ok I'll change it later thanks

**Comment by JoeBanks13** [comment]
Fixed in commit https://github.com/JoeBanks13/Music-Butt/commit/a3beccf0a99f765e3904230e0777759cba7bb15b and https://github.com/JoeBanks13/Music-Butt/commit/93015824496e82c1863c2d51ac16deff7150bd25
